USE customer_behavior;

SELECT * FROM mytable LIMIT 20;

1. what is the total revenue generated by male vs female customers?

select gender, sum(purchase_amount) as revenue
from mytable
group by gender;

2) which customer used a discount but still spent more then the averge
purchase amount

select customer_id, purchase_amount from mytable
where discount_applied = 'yes' and
purchase_amount >= (select avg(purchase_amount) from mytable); 

3) which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) as "averge product rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

4) compare the averge purchase amounts between standard and express shipping

select shipping_type, avg(purchase_amount)
from mytable
where shipping_type in ('standard','express')
group by shipping_type;

5) do subcribe customer spend more? compare average spend and total revenue between subcribers and non-subscribers

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

6) which 5 prodcut have the highest percentage of purchase with discounts applied?


select item_purchased, round(sum(case when discount_applied = 'yes' then 1 else 0 end) 
/ count(*) * 100,2) as discount_rate 
from mytable
group by item_purchased 
order by discount_rate
limit 5;

7)seement customers into row, returning, and loyal based on their total number of previous purchases, and show the count of each segemnet.

with customer_type as (
select 
customer_id, previous_purchases,
case when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from mytable)
select customer_segment, count(*) as number_of_customers
from customer_type group by customer_segment;

8) what are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

9)are customer who are repeat buyers also likely to subscription

select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status


10)what is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;








